name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test

      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.TOKEN }}
          lcov-file: ./coverage/lcov.info

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    needs: unit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.TOKEN }}

  e2e_test:
    name: Executar testes e2e
    runs-on: ubuntu-latest
    needs: unit

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: RafaelFerSilva/automacao_site_automation_pratice
          path: automacao_site_automation_pratice

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      - uses: nanasess/setup-chromedriver@master
      - run: chromedriver --url-base=/wd/hub &

      - name: Criar a pasta de reports
        run: |
          cd automacao_site_automation_pratice/
          mkdir reports
          
      - name: Instalar as dependências do Robot Framework
        run: |
          cd automacao_site_automation_pratice/
          pip install -r requirements.txt
      - name: Executar os tests e2e
        run: robot  --variable BROWSER:"headlesschrome" --outputdir ./automacao_site_automation_pratice/reports --loglevel TRACE --pythonpath ./automacao_site_automation_pratice/resources --exclude known_issue --exclude skip  ./automacao_site_automation_pratice/tests

      - name: Upload test reports
        uses: actions/upload-artifact@v1
        continue-on-error: true
        if: always()
        with:
          name: reports
          path: automacao_site_automation_pratice/reports
