name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test

      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.TOKEN }}
          lcov-file: ./coverage/lcov.info

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: 'coverage/clover.xml'
          threshold_alert: 85
          threshold_warning: 80
