name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test

      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.TOKEN }}
          lcov-file: ./coverage/lcov.info

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.TOKEN }}

  e2e_test:
    name: Executar testes e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: RafaelFerSilva/automacao_site_automation_pratice
          path: automacao_site_automation_pratice

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

      # - run: (Get-Item (Get-Command chrome).Source).VersionInfo.ProductVersion

      - uses: nanasess/setup-chromedriver@master
      - run: chromedriver --url-base=/wd/hub &

      - name: Criar a pasta de reports
        run: |
          cd ${{ github.workspace }}/
          mkdir reports
          
      - name: Instalar as dependências do Robot Framework
        run: |
          cd ${{ github.workspace }}/
          pip install -r requirements.txt
      - name: Executar os tests e2e
        run: robot  --variable BROWSER:"headlesschrome" --outputdir ${{ github.workspace }}/reports --loglevel TRACE --pythonpath ./resources --exclude known_issue --exclude skip  ${{ github.workspace }}/tests

      - name: Upload test reports
        uses: actions/upload-artifact@v1
        continue-on-error: true
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports

      - name: Comment E2E - PR Informations
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            **E2E - PR Informations**
            **PR Owner and repository:** ${{ github.repository }}
            **PR branch:** ${{ github.head_ref }}
            **Checkout Robot branch:** ${{ env.branch }}
          repo-token: ${{ secrets.TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: true

